version: "3"

services:
  web:
    image: nginx:latest
    ports:
      - 8080:80
    volumes:
      - ./src:/app
      - ./site.conf:/etc/nginx/conf.d/site.conf
    links:
      - php
      - mysql
    environment:
      DB_HOST: mysql
      DB_DATABASE: phpdocker
      DB_USERNAME: app
      DB_PASSWORD: password
      REDIS_HOST: redis
      SESSION_DRIVER: redis
      CACHE_DRIVER: redis

  php:
    build:
      context: .
      dockerfile: .docker/PHP-Dockerfile

  mysql:
    image: mysql:latest
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: phpdocker
      MYSQL_USER: app
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password

  redis:
    image: redis
    ports:
      - 6379:6379
